/*
 * Copyright (c) 2007, 2008 University of Tsukuba
 * Copyright (C) 2007, 2008 
 *      National Institute of Information and Communications Technology
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * 1. Redistributions of source code must retain the above copyright notice,
 *    this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright notice,
 *    this list of conditions and the following disclaimer in the documentation
 *    and/or other materials provided with the distribution.
 * 3. Neither the name of the University of Tsukuba nor the names of its
 *    contributors may be used to endorse or promote products derived from
 *    this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 */

// Secure VM Project
// maketestfs
// 
// By dnobori@cs.tsukuba.ac.jp

// maketestfs プログラム
//  UNIX 環境でユーザーモードで実行します。
// 
//  使用方法: maketestfs ファイル1 [ファイル2]...
// 
//  このプログラムを使用すると、指定した各ファイルの中身のデータを
//  バイナリデータ (unsigned char[] 配列) として埋め込んだ C ソースコード
//  とその C ソースコードを使用するためのヘッダファイルが自動生成されます。
//  C ソースコードは testfs.c、ヘッダは testfs.h という名前で生成されます。
// 
//  bitvisor に VPN クライアントモジュールを組み込む際に、将来的には
//  bitvisor が提供する小さな設定データ保存領域や IC カード内のデータ
//  を参照するようにすべき部分を、開発時に動作検証するために使用しています。
// 
//  具体的には、テスト用の証明書ファイル (X.509) や署名に使用する秘密鍵データ
//  (RSA)、VPN クライアントの設定ファイル (config.txt) の内容を bitvisor.elf
//  内に埋め込むために使用します。

#include <stdio.h>
#include <ctype.h>
#include <stdlib.h>
#include <string.h>
#include <stdarg.h>

#define	OUTPUT_C	"testfs.c"
#define	OUTPUT_H	"testfs.h"

#define	BUFSIZE		(8 * 1024)

#define	BYTES_PER_LINE	14


void write_str(FILE *f, char *str)
{
	fwrite(str, 1, strlen(str), f);
}

void write_format(FILE *f, char *str, ...)
{
	char tmp[BUFSIZE];
	va_list args;

	va_start(args, str);

	vsprintf(tmp, str, args);

	va_end(args);

	write_str(f, tmp);
}

int getfilesize(FILE *f)
{
	long size, old;

	old = ftell(f);
	fseek(f, 0, SEEK_END);
	size = ftell(f);
	fseek(f, old, SEEK_SET);

	return size;
}

int main(int argc, char *argv[])
{
	FILE *c, *h;
	int i;
	int num_files;

	printf("maketestfs Utility Program\n\nCopyright (c) 2007, 2008 University of Tsukuba. All Rights Reserved.\n\n");
	if (argc <= 1)
	{
		printf("  Usage: maketestfs FILE1 [FILE2]...\n\n");
		return 0;
	}

	c = fopen(OUTPUT_C, "wb");
	h = fopen(OUTPUT_H, "wb");

	write_str(c, "// testfs.c\n\n// Copyright (c) 2007, 2008 University of Tsukuba.\n// All Rights Reserved.\n\n// This file was generated by maketestfs. Do not edit manually.\n\n");
	write_str(c, "#include \"testfs.h\"\n\n");

	num_files = argc - 1;

	for (i = 0;i < num_files;i++)
	{
		char *filename = argv[i + 1];
		FILE *f;
		int fno = i + 1;
		int size;
		int j;
		unsigned char *data;

		f = fopen(filename, "rb");
		if (f == NULL)
		{
			printf("  Error: Cannot open \"%s\".\n", filename);
			return 0;
		}

		size = getfilesize(f);

		data = malloc(size);
		fread(data, 1, size, f);

		printf("File %u: %s:  %u bytes.\n", fno, filename, size);

		write_format(c, "// filename: \"%s\"\n", filename);
		write_format(c, "// filesize: %u bytes\n", size);
		write_format(c, "static char *testfs_name_file%u = \"%s\";\n", fno, filename);
		write_format(c, "static unsigned char testfs_data_file%u[] = {\n", fno);

		write_format(c, "#if\t0\n// contents of file \"%s\" (%u bytes):\n", filename, size);

		write_str(c, "\t// ");
		for (j = 0;j < size;j++)
		{
			if (data[j] == 13 || data[j] == 10)
			{
				if (data[j] == 13)
				{
					j++;
				}
				write_str(c, "\n\t//\t");
			}
			else
			{
				if (data[j] == '\t' || data[j] >= 32)
				{
					char ch[2];
					ch[0] = data[j];
					ch[1] = 0;
					write_str(c, ch);
				}
			}
		}

		write_format(c, "\n\n#endif\n");

		for (j = 0;j < size;j += BYTES_PER_LINE)
		{
			int block_size = size - j;
			int k;
			if (block_size >= BYTES_PER_LINE)
			{
				block_size = BYTES_PER_LINE;
			}
			write_format(c, "\t");
			for (k = j;k < (j + block_size);k++)
			{
				unsigned char ch = data[k];
				write_format(c, "0x%02x,", ch);
			}
			write_format(c, "\n");
		}
		write_format(c, "};\n");

		write_format(c, "static unsigned int testfs_size_file%u = sizeof(testfs_data_file%u);\n\n", fno, fno);

		free(data);
		fclose(f);
	}

	write_str(c, "static int testfs_strcmpi(const char *str1, const char* str2) {\n");
	write_str(c, "\tunsigned int i = 0;\n");
	write_str(c, "\twhile (1) {\n");
	write_str(c, "\t\tchar c1 = str1[i], c2 = str2[i];\n");
	write_str(c, "\t\tif ('A' <= c1 && c1 <= 'Z') c1 += 'z' - 'Z';\n");
	write_str(c, "\t\tif ('A' <= c2 && c2 <= 'Z') c2 += 'z' - 'Z';\n");
	write_str(c, "\t\tif (c1 > c2) return 1; else if (c1 < c2) return -1;\n");
	write_str(c, "\t\tif (!c1 || !c2) return 0; i++;\n");
	write_str(c, "\t}\n");
	write_str(c, "}\n\n");

	write_str(c, "// Load file data from testfs.\n");
	write_str(c, "int testfs_loaddata(const char *filename,\n");
	write_str(c, "\tvoid **ppdata, unsigned int *psize)\n");
	write_str(c, "{\n");

	for (i = 0;i < num_files;i++)
	{
		char *filename = argv[i + 1];
		int fno = i + 1;

		write_format(c, "\t// File \"%s\"\n", filename);
		write_format(c, "\tif (testfs_strcmpi(filename, testfs_name_file%u) == 0)\n", fno);
		write_str(c, "\t{\n");
		write_format(c, "\t\tif (ppdata) *ppdata = testfs_data_file%u;\n", fno);
		write_format(c, "\t\tif (psize) *psize = testfs_size_file%u;\n\n", fno);
		write_str(c, "\t\treturn 1;\n");
		write_str(c, "\t}\n\n");
	}

	write_str(c, "\treturn 0;\n");
	write_str(c, "}\n\n");

	write_str(h, "// testfs.h\n\n// Copyright (c) 2007, 2008 University of Tsukuba.\n// All Rights Reserved.\n\n// This file was generated by maketestfs. Do not edit manually.\n\n"
		"#ifndef	TESTFS_H\n#define	TESTFS_H\n\nint testfs_loaddata(const char *filename,\n\tvoid **ppdata, unsigned int *psize);\n\n#endif	// TESTFS_H\n\n");

	fclose(c);
	fclose(h);

	return 0;
}

