CONSTANTS-$(CONFIG_ENABLE_ASSERT) += -DENABLE_ASSERT
CONSTANTS-$(CONFIG_VTD_TRANS) += -DVTD_TRANS

CFLAGS += -Idrivers/include

objs-y += core.o
objs-y += dmar.o
objs-y += iommu.o
objs-y += pci.o
objs-y += pci_init.o
