CONSTANTS-$(CONFIG_ENABLE_ASSERT) += -DENABLE_ASSERT
CONSTANTS-$(CONFIG_VTD_TRANS) += -DVTD_TRANS

CFLAGS += -Idrivers/include

objs-1 += core.o
objs-1 += dmar.o
objs-1 += iommu.o
objs-1 += pci.o
objs-1 += pci_init.o
