CFLAGS += -Idevtree/libfdt

objs-y += libfdt/fdt.o
objs-y += libfdt/fdt_addresses.o
objs-y += libfdt/fdt_check.o
objs-y += libfdt/fdt_empty_tree.o
objs-y += libfdt/fdt_overlay.o
objs-y += libfdt/fdt_ro.o
objs-y += libfdt/fdt_rw.o
objs-y += libfdt/fdt_strerror.o
objs-y += libfdt/fdt_sw.o
objs-y += libfdt/fdt_wip.o
